name: Default

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig libfontconfig1-dev

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check clippy
        run: cargo clippy --tests --examples -- -D warnings

      - name: Check cargo doc
        run: cargo doc --no-deps

      - name: Build examples
        run: cargo build --examples

      - name: Run tests
        run: cargo test
