name: Default

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Check format
        run: cargo fmt -- --check

  lint:
    name: Check lint and docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

      - name: Run clippy
        run: cargo clippy --tests --examples -- -D warnings

      - name: Run cargo doc
        run: cargo doc --no-deps

  build_test:
    name: Build examples and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig libfontconfig1-dev

      - name: Build
        run: cargo build --examples

      - name: Check format
        run: cargo test
