on:
  push:
    tags:
      - "*"

name: Publish

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs:
    - rustfmt
    - lint
    - build_examples
    - test
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish crate
        run: |-
          cargo release \
                publish
                --workspace \
                --all-features \
                --allow-branch HEAD \
                --no-confirm \
                --no-verify \
                --execute
